# print("Assolom-u alekum!")
# print('Hi guys')
# print('lorem ipsum')
# print("men 'lenova' markasidagi kompyuter ishlataman ")
print("Odam borki odamlarning naqshidur, \n  Odam borki hayvon andin yaxshidur")
#Arifmetik amallar
print(5 + 6)
print(10 - 4)
print(12 * 3)
print(15 / 5, 12 * 5, 52 + 17, 65 -15)
print(65 // 5)
print(64 ** (1 / 2))
print(625 ** (1 / 4))
print(12 % 5)
print(4 % 7)
print("Beshning kvadrati", 5 ** 2, "ga teng")
#amaliyot
print("\"Nexia\", \"Tico\", 'Damas' ko'rganlar qilar havas")
print('"Nexia", "Tico", \'Damas\' ko\'rganlar qilar havas')
print("5-ning 4-darajasi ", 5 ** 4)
print("22 ni 4 ga bo'lganda qoldiq " , 22 % 4)
print("yuzi", 125 * 125, "perimetri", 125 * 4, "ga teng")
print("Diametri 12 ga teng bo'lgan doiraning yuzi", 3.14 * (12 ** 2))
print("Katetlari 6 va 7 bo'lgan to'g'ri burchakli uchburchakning gipotenuzasi", (6 ** 2 + 7 **2) ** (1 / 2), "ga teng")
print("Tomonlari 3, 4, 5 uchburchakning yuzi", (6 * (6 - 3) * (6 - 4) * (6 - 5)) ** (1 / 2), "ga teng")